import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bodoni = localFont({
  src: "../../public/fonts/BodoniModa-VariableFont_opsz,wght.ttf",
  variable: "--font-bodoni",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable}  ${geistMono.variable} ${bodoni.variable} h-full antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
